### ISSUE TITLE
viz roadmap

### ISSUE THREAD

**Issue by Athospd** [Athospd/upwork03#1]
## Vizualizations

- [x] viz 01: Poverty Scatterplot
- [x] viz 02: Correlation Heatmap 
- [x] viz 03: Time series trend
- [x] viz 04: Highest Incidence
- [x] viz 05: Incidence Growth
